[project]
name = "tokengate"
description = "Unique voting contract for project 08"
authors = ["solidworkssa"]
telemetry = false
cache_dir = ".cache"

[contracts.tokengate]
path = "contracts/tokengate.clar"

[repl.analysis]
passes = ["check_checker"]
